### ISSUE TITLE
Mismatch of your implementation and your paper's claim.

### ISSUE THREAD

**Issue by MerrillLi** [usail-hkust/BigST#1]
It seems like the proposed "linear_transformer" in preprocess stage is not used by BigST. 

Please check whether the code you upload is the right version. Thanks.

**Comment by hanjindong** [comment]
Thanks for pointing this out. In practice, we opt to store preprocessed features directly onto disk and load them during training to accelerate the training process.

To facilitate your understanding, I have added this function to the code as option. You can use linear_transformer during training by specifying the "use_long" argument.

**Comment by MerrillLi** [comment]
> Thanks for pointing this out. In practice, we opt to store preprocessed features directly onto disk and load them during training to accelerate the training process.
> 
> To facilitate your understanding, I have added this function to the code as option. You can use linear_transformer during training by specifying the "use_long" argument.

Thanks for your help. Now I can understand the workflow of your paper. Great work! Congratulations~
